use_frameworks!

platform :ios, '10.0'

target 'EasyKits_Example' do
  pod 'EasyKits', :path => '../'
  pod 'MJRefresh'
  pod 'Kingfisher'
  pod 'Then'
  
  pod 'ModuleA', :path => '../Module/ModuleA'
  pod 'ModuleB', :path => '../Module/ModuleB'
  
  pod 'ModuleAServices', :path => '../Module/ModuleAServices'
  pod 'ModuleBServices', :path => '../Module/ModuleBServices'
  pod 'ModuleServices', :path => '../Module/ModuleServices'
end
